# Generated by Django 2.0.13 on 2019-03-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SensorID', models.CharField(max_length=5)),
                ('Date_and_Time', models.CharField(max_length=30)),
                ('Temperature', models.IntegerField()),
                ('Humidity', models.IntegerField()),
                ('Light', models.IntegerField()),
            ],
        ),
    ]
